---
layout: academic
title: 薛朝阳
permalink: /chinese/
site_route: home
initial_language: zh
---
<section class="hero"><p class="eyebrow">大气化学 · 生物圈—大气交换</p><h1>探索地表与大气之间的<br><em>化学过程。</em></h1><p class="intro">我是薛朝阳，中国科学院大气物理研究所研究员。我的研究关注活性氮化学与生物圈—大气交换，探索这些过程如何影响大气氧化能力、空气质量和气候。</p><p class="intro">通过野外观测、实验室实验与大气模型，研究 HONO 来源及地表交换过程，并开发和应用大气成分与通量测量系统。</p><div class="hero-actions"><a href="/publications/" class="primary-link">查看研究论文 <span>↗</span></a><a href="/research/" class="text-link">研究方向 →</a></div></section>
      <div class="research-strip"><div><span class="num">01</span><h3>活性氮化学</h3><p>HONO 来源、转化过程与大气氧化。</p></div><div><span class="num">02</span><h3>生物圈—大气交换</h3><p>土壤、生态系统与大气之间的化学交换。</p></div><div><span class="num">03</span><h3>观测与模型</h3><p>用仪器研发和外场观测约束大气化学过程。</p></div></div>
      <section><div class="section-heading"><h2>近期论文</h2><a href="/publications/">全部论文 →</a></div><article class="pub"><div class="pub-year">2026</div><div><h3><a href="https://doi.org/10.5194/acp-26-5313-2026" target="_blank" rel="noopener noreferrer">Impacts of summertime photochemical aging on the physicochemical properties of aerosols in a Paris suburban forest region</a></h3><p class="pub-meta">Atmospheric Chemistry and Physics · 26, 5313–5332</p><div class="pub-links"><a href="https://doi.org/10.5194/acp-26-5313-2026" target="_blank" rel="noopener noreferrer">阅读论文 ↗</a></div></div></article><article class="pub"><div class="pub-year">2026</div><div><h3><a href="https://doi.org/10.1021/acs.est.5c17068" target="_blank" rel="noopener noreferrer">Remarkable Overestimation of Soil N₂O Emission by Using Static Chambers</a></h3><p class="pub-meta">Environmental Science &amp; Technology · 60, 8671–8680</p><div class="pub-links"><a href="https://doi.org/10.1021/acs.est.5c17068" target="_blank" rel="noopener noreferrer">阅读论文 ↗</a></div></div></article><article class="pub"><div class="pub-year">2026</div><div><div class="role">第一作者 · 共同通讯作者<span class="type">观点文章</span></div><h3><a href="https://doi.org/10.1021/acs.est.6c01723" target="_blank" rel="noopener noreferrer">Changing Emissions and Atmospheric Chemistry: Ongoing Impacts on Air Quality and Climate</a></h3><p class="pub-meta">Environmental Science &amp; Technology · 60, 5910–5920</p><div class="pub-summary"><p>讨论排放控制与能源转型如何改变二次气溶胶、活性氮和持久性污染物的环境过程。</p><p>提出连接排放变化、大气化学与环境暴露的研究重点，支撑空气质量和气候的协同评估。</p></div><div class="pub-links"><a href="https://doi.org/10.1021/acs.est.6c01723" target="_blank" rel="noopener noreferrer">阅读论文 ↗</a></div></div></article></section>
